# Generated by Django 3.1.3 on 2020-12-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201117_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
